### PR TITLE
Update from Mozilla repository

### PR DESCRIPTION
**Pull request by maspalio**
A light refreshment of certificates lineup might help, whenever you have any tuits for that.
A slight caveat though, it might be urgent to wait for the conclusion about supposedly rogue CAs like WoSign (and most likely others) as per [CA:WoSign Issues](https://wiki.mozilla.org/CA:WoSign_Issues).
Thanks!

### CODE REVIEW

**Comment by jonjensen** [comment]
Note that a newer batch of certificates dated 2016-11-02 is now available from https://curl.haxx.se/docs/caextract.html - we are using this in an internally-maintained version of Mozilla::CA.

**Comment by abh** [comment]
Done in #10, apologies it took so long.

**Comment by jonjensen** [comment]
@abh Thanks!

**Comment by maspalio** [comment]
Thanks!

**Pull request closed without merging**
